#!/usr/bin/env python3
"""
B 站 UP 主快速分类 - 7 天时间窗 (5-10 分钟)
"""

import sys
import os
import json
import asyncio
from datetime import datetime, timedelta
from pathlib import Path
from typing import List, Dict
from collections import Counter

sys.path.insert(0, str(Path(__file__).parent))
from up_classify_active import find_active, fetch_all_followings
from up_classifier import keyword_fallback, DEFAULT_CATEGORIES
from bilibili_cc import load_credential

OUTPUT_DIR = Path.home() / "my_bili_data"


async def main():
    cd = load_credential()
    uid = int(cd.get("dedeuserid", 0))
    sessdata = cd.get("sessdata", "")
    bili_jct = cd.get("bili_jct", "")

    cache_30 = OUTPUT_DIR / "active_ups_30day.json"
    if cache_30.exists():
        age = (datetime.now().timestamp() - cache_30.stat().st_mtime) / 3600
        if age < 6:
            print(f"用 30 天缓存 (年龄 {age:.1f}h)")
            active = json.loads(cache_30.read_text())
        else:
            print("重新扫描 (30 天时间窗)...")
            ups = await fetch_all_followings(uid, sessdata, bili_jct)
            print(f"总关注: {len(ups)}")
            active = await find_active(ups, days=30)
            cache_30.write_text(json.dumps(active, ensure_ascii=False))
            print(f"30天活跃: {len(active)}")
    else:
        print("扫描 30 天活跃...")
        ups = await fetch_all_followings(uid, sessdata, bili_jct)
        print(f"总关注: {len(ups)}")
        active = await find_active(ups, days=30)
        cache_30.write_text(json.dumps(active, ensure_ascii=False))
        print(f"30天活跃: {len(active)}")

    # 关键词粗分
    print("关键词粗分...")
    for up in active:
        r = keyword_fallback(up["name"], up.get("sign", ""), [], DEFAULT_CATEGORIES)
        up["category"] = r["category"]
        up["confidence"] = r["confidence"]
        up["topics"] = r.get("topics", [])
    by_cat = Counter(u["category"] for u in active)
    print(f"\n分类分布: {dict(by_cat.most_common())}")

    # 报告
    today = datetime.now().strftime("%Y-%m-%d")
    lines = [
        f"# 活跃 UP 主分类报告 - {today}",
        "",
        "## 📊 总览",
        f"- **月活 UP 主**: {len(active)}",
        f"- **时间窗**: 过去 30 天",
        "",
        "## 📂 分类分布",
        "",
    ]
    for cat in DEFAULT_CATEGORIES + ["其他"]:
        n = by_cat.get(cat, 0)
        if n > 0:
            pct = n / max(1, len(active)) * 100
            lines.append(f"- **{cat}**: {n} 个 ({pct:.1f}%)")

    # 详细
    for cat in DEFAULT_CATEGORIES + ["其他"]:
        cat_ups = [u for u in active if u["category"] == cat]
        if not cat_ups:
            continue
        lines.append("")
        lines.append(f"## 📂 {cat} ({len(cat_ups)} 个)")
        lines.append("")
        for up in cat_ups[:50]:  # 限 50 个
            lines.append(f"- **{up['name']}** (UID: {up['mid']})")
            sign = up.get("sign", "")[:80]
            if sign:
                lines.append(f"  - 签名: {sign}")
            topics_str = " ".join(f"`{t}`" for t in up.get("topics", [])) or "—"
            lines.append(f"  - 话题: {topics_str}")
            recent = up.get("recent_videos", [])
            if recent:
                lines.append(f"  - 最新: {recent[0]['created_str']} - {recent[0]['title'][:50]}")
        if len(cat_ups) > 50:
            lines.append(f"- ... 及其他 {len(cat_ups) - 50} 个")
    lines.append("")
    lines.append("---")
    lines.append(f"*Generated by up_classify_quick v1.0*")

    out_md = OUTPUT_DIR / "up_classify_active.md"
    out_md.write_text("\n".join(lines), encoding="utf-8")
    print(f"\n报告: {out_md}")

    # 数据
    data_out = OUTPUT_DIR / "active_ups_data.json"
    data_out.write_text(json.dumps(active, ensure_ascii=False), encoding="utf-8")
    print(f"数据: {data_out}")

    # 画图 (按分类)
    print("画大图...")
    from up_classify_active import draw_active_graph
    out_png = OUTPUT_DIR / "up_classify_active_graph.png"
    await asyncio.to_thread(draw_active_graph, active, out_png)
    print(f"图: {out_png}")


if __name__ == "__main__":
    asyncio.run(main())
